[package]
name = "witness"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
witness =  "0x0"
sui =  "0000000000000000000000000000000000000002"
